### ISSUE TITLE
StreamMediaServerKeeper报错：Data Exception

### ISSUE THREAD

**Issue by LGxxxxxx** [chatop2020/StreamNode-GB28181#13]
运行StreamMediaServerKeeper时报错
2020-11-16 19:02:47,471 [7] ERROR StreamNode - 报错了-> Object reference not set to an instance of an object. ->    at StreamMediaServerKeeper.ProcessApis.CheckIsRunning(ResponseStruct& rs) in /work/StreamNode_1116/StreamNode-GB28181-master/StreamMediaServerKeeper/ProcessApis.cs:line 145
   at StreamMediaServerKeeper.Common.KeepAlive() in /work/StreamNode_1116/StreamNode-GB28181-master/StreamMediaServerKeeper/Common.cs:line 456

**Comment by XtosX** [comment]
我在编译时就不行，哈，晕
[root@localhost StreamNodeWebApi]# dotnet run
Starting logging initialisation.
Unhandled exception. System.TypeInitializationException: The type initializer for 'CommonFunctions.Common' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GB28181.Servers.SIPMessage.SIPMessageCore.Start() in /usr/local/streamnode28181/GB28181.SIPSorcery/Servers/SIPMessage/SIPMessageCore.cs:line 327
   at LibGB28181SipGate.SipCoreHelper.Start() in /usr/local/streamnode28181/LibGB28181SipGate/SipCoreHelper.cs:line 963
   at CommonFunctions.Common..cctor() in /usr/local/streamnode28181/CommonFunctions/Common.cs:line 58
   --- End of inner exception stack trace ---
   at StreamNodeWebApi.Program.<>c.<CreateHostBuilder>b__3_0(IWebHostBuilder webBuilder) in /usr/local/streamnode28181/StreamNodeWebApi/Program.cs:line 31
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.<>c__DisplayClass0_0.<ConfigureWebHostDefaults>b__0(IWebHostBuilder webHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at StreamNodeWebApi.Program.CreateHostBuilder(String[] args) in /usr/local/streamnode28181/StreamNodeWebApi/Program.cs:line 28
   at StreamNodeWebApi.Program.Main(String[] args) in /usr/local/streamnode28181/StreamNodeWebApi/Program.cs:line 24

**Comment by chatop2020** [comment]
整理好你的目录结构，运行streamnode需要root权限
